#!name=Apple WLOC 定位修改
#!desc=修改 Apple 網路定位回傳座標 (Shadowrocket 小火箭) | 快捷指令(推薦): 設定地理位置 https://www.icloud.com/shortcuts/a82717d8fdad4e6280866fcf911173f7 清除恢復位置 https://www.icloud.com/shortcuts/f42632d406504f24a2cd163af4fe012f | 選點頁面: https://wloc-spoofer.trend0522.workers.dev/
#!author=ios151 Rewrite (fork by trend0522)
#!homepage=https://github.com/trend0522/wloc-spoofer
#!icon=https://raw.githubusercontent.com/trend0522/wloc-spoofer/refs/heads/main/wloc.jpg
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/(?:gs-loc(?:-cn)?\.apple\.com|gsp-ssl\.ls\.apple\.com|bluedot\.is\.autonavi\.com(?:\.gds\.alibabadns\.com)?)\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/trend0522/wloc-spoofer/refs/heads/main/dist/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&randomRadius=0&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/trend0522/wloc-spoofer/refs/heads/main/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com, gsp-ssl.ls.apple.com, bluedot.is.autonavi.com, bluedot.is.autonavi.com.gds.alibabadns.com
